version: '2'
services:
  auth:
    build: .
    environment:
      RETHINK_HOST: rethinkdb
      RETHINK_PORT: 28015
      RETHINK_NAME: auth
      PORT: 3000
      JWT_SECRET: testsecret
      API_KEY: hai
    depends_on:
      - rethinkdb
    links:
      - rethinkdb
  rethinkdb:
    image: rethinkdb
